# More option see https://github.com/Eric-Guo/wechat#menu-create
button:
  -
    type: view
    name: wechat
    url: "http://ag4uqr.natappfree.cc/auth/wechat"
#  -
#    type: view
#    name: 个人中心
#    url: "http://2m4nh9.natappfree.cc/users"